### ISSUE TITLE
How can I load an ONNX model into raf?

### ISSUE THREAD

**Issue by ikaroso** [awslabs/raf#118]
Hi, it is said in the doc that raf supports ONNX, but I cant find how to load an ONNX model in raf.

**Comment by hgt312** [comment]
Some description in wiki is out of date. RAF does not have a ONNX frontend now.
To load a ONNX model, use TVM's ONNX frontend with RAF pass `FromRelay` may works. FYI: https://github.com/awslabs/raf/blob/main/python/raf/frontend/pytorch.py
