### ISSUE TITLE
[Todo] Debug Dropout Support

### ISSUE THREAD

**Issue by whbldhwj** [awslabs/raf#52]
The current three commits on dropout are buggy and need to be fixed.
1. 249db5f7b64522fd5912c95b5eb285eb6b8d10ff
2. 5ac70e6912b8f22fe4f17d8787bcec180737f0b8
3. e9137ee53c916d4fc524dfeaa7eb53b5fc4e5adf

**Comment by comaniac** [comment]
Problem disappeared with the latest commit.
